### ISSUE TITLE
Bug: Duplicated tables

### ISSUE THREAD

**Issue by niem94** [edandersen/core-admin#10]
When I set this admin panel up with a DbContext that extends `ApiAuthorizationDbContext<ApplicationUser>` to authenticate with IdentityServer, I get duplicated DbSets.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/26203420/128714664-ba296896-4648-4e67-943c-700cb74a4261.png">

Is there a way to ensure it does not list DbSet's if they are already listed? Or filter DbSets, to only show e.g. `Users` and `Roles` as well as my custom DbSets such as `Ecosystems`.

EDIT:
I think the duplicated `DbSet`s are caused by this code when a user inherits from a subtype of `DbContext`:

```csharp
private static void FindDbContexts(IServiceCollection services)
{
    foreach (var service in services.ToList())
    {
        if (service.ImplementationType == null)
            continue;
        if (service.ImplementationType.IsSubclassOf(typeof(DbContext)))
        {
            services.AddTransient(services => new DiscoveredDbContextType() { Type = service.ImplementationType });
        }
    }
}
```
I suspect the services collection contains multiple references to the implemented `DbContext` so it can be resolved from all its inherited interfaces. As such, I believe a `DiscoveredDbContext`is added for each found subtype of `DbContext` even though they reference the same implemented `DbContext`. Maybe a check can be made to check whether a `DbContext` has already been processed, and in that case, it can be skipped, so the `DbSet`s are no longer duplicated.

I hope this helps! :-)

**Comment by edandersen** [comment]
Thanks so much for spotting this. Maybe an overload for AddCoreAdmin() that takes a type of DbContext to constrain it could work?

**Comment by niem94** [comment]
Yeah, this would definitely work, but a way to support not adding multiple dbContexts by default, would be nice.

Do you mind me making a PR for this, when i have the time?

**Comment by edandersen** [comment]
Absolutely I accept PRs!
