### ISSUE TITLE
 Improve Performance by Providing an Option to Disable Foreign Key Drop-Downs

### ISSUE THREAD

**Issue by mutazzuhairi** [edandersen/core-admin#108]
**We are experiencing performance issues in the CoreAdmin interface, particularly on the "Create" tab, when dealing with entities that have foreign key relationships. The current implementation automatically generates drop-down lists for foreign key fields by querying and displaying all related records. This approach significantly impacts performance, especially when the related tables contain a large number of records.**

To improve the performance and usability of CoreAdmin, we propose adding an option to disable the automatic generation of drop-down lists for foreign key fields. Instead, users should have the ability to input values as free text or leverage column data types to determine the appropriate input method. This enhancement would provide more flexibility and prevent unnecessary performance overhead associated with loading large datasets.

So, if you can Introduce a configuration setting that allows administrators to disable drop-down generation for foreign key fields and to use the column data type to determine the input method for foreign key fields.

![2024-06-08 15 14 36](https://github.com/edandersen/core-admin/assets/47029836/55441cf3-91b6-41db-9205-f1bdc63b997f)

**Comment by edandersen** [comment]
Thanks for the ticket. The screenshot shows the queries taking 3ms and 6ms though?

Also out of curiosity who is "we"?

________________________________
From: Mutaz Zuhairi ***@***.***>
Sent: Saturday, June 8, 2024 9:16:24 PM
To: edandersen/core-admin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [edandersen/core-admin] Improve Performance by Providing an Option to Disable Foreign Key Drop-Downs (Issue #108)


We are experiencing performance issues in the CoreAdmin interface, particularly on the "Create" tab, when dealing with entities that have foreign key relationships. The current implementation automatically generates drop-down lists for foreign key fields by querying and displaying all related records. This approach significantly impacts performance, especially when the related tables contain a large number of records.

To improve the performance and usability of CoreAdmin, we propose adding an option to disable the automatic generation of drop-down lists for foreign key fields. Instead, users should have the ability to input values as free text or leverage column data types to determine the appropriate input method. This enhancement would provide more flexibility and prevent unnecessary performance overhead associated with loading large datasets.

So, if you can Introduce a configuration setting that allows administrators to disable drop-down generation for foreign key fields and to
2024-06-08.15.14.36.png (view on web)<https://github.com/edandersen/core-admin/assets/47029836/55441cf3-91b6-41db-9205-f1bdc63b997f>
use the column data type to determine the input method for foreign key fields.

**Comment by mutazzuhairi** [comment]
Hey @edandersen 
Sorry for the context, I meant me.

Yes, it took 3ms since I tried it on a small table. Is there an option to improve this functionality or to disable it?

**Comment by edandersen** [comment]
No there isn't an option at the moment. I accept PRs though.

If this is being used commercially please respect the license or contact me for a custom license.

________________________________

**Comment by mutazzuhairi** [comment]
No commercial use. I used it for testing my personal tools. It was just a question. I decided not to use it again; I will look for another tool. Thank you.
