### ISSUE TITLE
Feature proposal: Enable filtering what tables to show

### ISSUE THREAD

**Issue by niem94** [edandersen/core-admin#12]
In some cases showing all tables can be confusing for the end-user, and it would be nice if we were able to filter what tables are shown in the admin panel, such that only the stuff relevant to the person using the admin panel is shown.

I suggest adding an inclusive or exclusive list to the `AddCoreAdmin`extension method parameters that exclude or include all matching DbSets found in the list. If this is an optional parameter, it can default to the current behavior if left out of the call.

Ps. I removed all info regarding this issue in my other issue (#10), so issue #10 is only concerned with duplicated tables.

**Comment by niem94** [comment]
I would not mind creating a PR for this if you agree with the approach and agree that the feature is useful.

I propose to add an optional IFilterOptions parameter to the `AddCoreAdmin` method that accepts either an inclusive list or an exclusive list of `DbSet`´s to exclude or include. I then want to use this list to match against the Views that present the data.

@edandersen do you like this approach, or do you have something else in mind? :-)

**Comment by andi0b** [comment]
I thought about that too already. I would prefer a [fluent configuration interface][1], comparable to the EF core model builder. There are so many things that should be customizable, for example:

On entity level and on field level I would like to see
- hide/show tables/fields
- rename, description
- allow/forbid adding, editing, deleting
- additional validation rules, default values, ...
- default sort order
- ...

something like this (pseudocode):
```csharp
adminBuilder.Entity<Person>()
    .Exclude();

adminBuilder.Entity<Address>()
    .OrderBy(p=>p.ZipCode)
    .Name("Customer Addresses")
    .Description("Contains all the contacts of all customers");

adminBuilder.Entity<Address>
    .Field(e=>e.ZipCode)
    .ReadOnly();
```
    
[1]: https://docs.microsoft.com/en-us/ef/core/modeling/#use-fluent-api-to-configure-a-model

**Comment by edandersen** [comment]
A rudimentary way of doing this has been added to 1.8.0 under "filtering entity types"

I will definitely look at a proper fluent interface for 2.0.0.

**Comment by niem94** [comment]
Thank you a bunch! This is exactly what I needed 😃
