### ISSUE TITLE
Autogenerate ID in create

### ISSUE THREAD

**Issue by vorotynsky** [edandersen/core-admin#13]
Disable field for autogenerated primary keys in a create view.

it is inconvenient to create a new record and fill in the ID yourself.

**Comment by SolarLatamCode** [comment]
Plus one

**Comment by Brouilles** [comment]
Agree!

**Comment by edandersen** [comment]
This is implemented in 1.7.0. If am entity property has a ```DatabaseGenerated``` attribute, it won't appear on the Create form and will be autogenned by the DB.
