### ISSUE TITLE
Double type verification problem

### ISSUE THREAD

**Issue by Brouilles** [edandersen/core-admin#20]
Hi,
I have updated to the last version. No matter the value (except integer), a double input show `The field Price must be a number.`.
At the beginning, I thinking of a problem of localization (my browser is in French. So it used a comma, not a dot. But even with a dot, the problem is the same.

Here a screenshot of the DemoApp (in my fork, but the problem is the same with the 1.7.0).
![image](https://user-images.githubusercontent.com/1573282/132878160-0be37ab6-690f-413e-a0bf-b74ebe537882.png)

**Comment by edandersen** [comment]
Hi, in 1.8.0 I've made it so that commas are also accepted. Whilst the culture on the server will still need to be correct, this should at least low French users to use commas (or periods) here.
