### ISSUE TITLE
Dark theme for the dashboard

### ISSUE THREAD

**Issue by Brouilles** [edandersen/core-admin#29]
A good idea would be to set up a dark theme in addition to the default light.
I am working on it currently. If somebody is interested, don't hesitate to ping me!

I have planned to make a PR when done. To see later if it could be integrated into master.

**Comment by Brouilles** [comment]
![image](https://user-images.githubusercontent.com/1573282/147594007-99744eae-494e-4a70-9b91-924d2b1de398.png)

**Comment by Brouilles** [comment]
An enhancement can be adding a button to switch between themes. With saving in a cookie the configuration.

Currently it is using the system value. And for older browsers like IE, the default theme is light.

**Comment by edandersen** [comment]
Merged into 2.2.0 :)
