### ISSUE TITLE
Host a demo on Microsoft Azure free tier

### ISSUE THREAD

**Issue by Brouilles** [edandersen/core-admin#31]
Why not host the `DotNetEd.CoreAdmin.DemoAppDotNet6` project on Microsoft Azure free tier? As a demo.
Don't know if it is possible to reset data automatically.

**Comment by Brouilles** [comment]
Stop me if I have wrong. But the demo use an in memory database. And by default Azure stop the instance after I time without requests. And recreate it when needed. 

So, the database is automatically cleaned.

**Comment by Brouilles** [comment]
No news about it? @edandersen

**Comment by edandersen** [comment]
We are now live at https://core-admin-demo.azurewebsites.net/ :)
