### ISSUE TITLE
Add Markdown input

### ISSUE THREAD

**Issue by Brouilles** [edandersen/core-admin#33]
It seems essential to me to allow the user to define an entry with the Markdown editor in the backend. For blog or similar. Maybe we can use https://github.com/Ionaru/easy-markdown-editor (same as OrchardCMS).

**Comment by Brouilles** [comment]
![image](https://user-images.githubusercontent.com/1573282/149634438-30a8898c-8fa0-4a2a-b281-c0aeeb9e53b7.png)

With the DataType `[DataType("Markdown")]`.

**Comment by Brouilles** [comment]
https://github.com/edandersen/core-admin/pull/37

**Comment by edandersen** [comment]
Legend, this is now merged :)
