### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by Sl4vP0weR** [edandersen/core-admin#4]

**Comment by edandersen** [comment]
I was going to take a look at this shortly :-)

**Comment by edandersen** [comment]
Turns out it supports enums on the Edit/Create views, just not on the grid. I will struggle to add it to the grid so will close this. Thanks :)

**Comment by Sl4vP0weR** [comment]
> Turns out it supports enums on the Edit/Create views, just not on the grid. I will struggle to add it to the grid so will close this. Thanks :)

When you will add it ?
