### ISSUE TITLE
foreign key values not filled

### ISSUE THREAD

**Issue by cetindogu** [edandersen/core-admin#46]
maybe first string column must be fetched

![image](https://user-images.githubusercontent.com/7325611/151608594-d19e5cc6-5092-4b3b-b82e-e33d4fa05762.png)

**Comment by edandersen** [comment]
You need to provide a ToString() method on your entities.

**Comment by hm2075** [comment]
You can't really be doing that if you are using database first approach,     

Sometimes database changes are done by dba teams only and then rescaffold each time
