### ISSUE TITLE
Override MVC Grid Templates

### ISSUE THREAD

**Issue by cornelha** [edandersen/core-admin#47]
I have noticed that with a new dotnet 6 project (haven't tested any others) that the admin panel is now served as an SPA of some sort, how would one go about overriding/customising the MVC-Gird views and styles?

**Comment by edandersen** [comment]
If you add copies of the Views into your own project with exactly the same path, your versions will override the core admin ones and you can customize them.

**Comment by cornelha** [comment]
Awesome, thank you
