### ISSUE TITLE
Show foreign table NAME instead of ID on grid view

### ISSUE THREAD

**Issue by haroldocampo** [edandersen/core-admin#53]
In the edit view this was done possible (good job) by overriding the ToString function on entity model. Is it also possible to implement this also on grid view?

It would be also nice if the foreign column could be a clickable link that redirect the user to the foreign table, that is filtered to the specific row clicked on the parent table 💪

**Comment by edandersen** [comment]
The ToString is now used on the Grid view too in 2.5.0.

The second item I probably won't address just yet.
