### ISSUE TITLE
Not nullable foreign keys on entity cause error

### ISSUE THREAD

**Issue by PawelZygmax** [edandersen/core-admin#55]
Only nullable foreign keys in entity works as expected - empty field in dropdown, etc.
[Key]
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
[Display(AutoGenerateField = false)]
public int Id { get; set; }

public string Name { get; set; }

[Display(AutoGenerateField = false)] // prevent showing on the grid
public int? CategoryId { get; set; }

[ForeignKey("CategoryId")]
public Category? Category { get; set; }

Declaring foreign key without question mark makes core admin not being able to add entity.

**Comment by jacksonrakena** [comment]
+1 for this issue. This also blocks CoreAdmin from supporting ASP.NET Identity by default, as the default Identity objects use nullable foreign keys.

**Comment by edandersen** [comment]
Rollback to 2.4.0 until this is addressed :-)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by edandersen** [comment]
This should be addressed in 2.5.1 going out shortly. Please reopen if not addressed. You'll need to make sure non-nullable foreign keys have the ForeignKey data attribute.
