### ISSUE TITLE
Edit screen shows DatabaseGenerated fields when Create doesn't

### ISSUE THREAD

**Issue by PawelZygmax** [edandersen/core-admin#56]
Despite adding Annotations over Id like this:

  [Display(AutoGenerateField = false)]
  [Key]
  [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
  public int Id { get; set; }

field id is generated in edit mode, when adding new entity it works fine

**Comment by edandersen** [comment]
Addressed in 2.5.1. Please reopen if not fixed.
