### ISSUE TITLE
Admin not working

### ISSUE THREAD

**Issue by PeterZhukov** [edandersen/core-admin#7]
StartupSQLite.cs(34,13): error CS1061: 'IServiceCollection' does not contain a definition for 'AddCoreAdmin' and no accessible extension method 'AddCoreAdmin' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?) [/home/user/projects/net_admin/AspNetCore.Docs/aspnetcore/data/ef-rp/intro/samples/cu30/ContosoUniversitySQLite.csproj]

The build failed. Fix the build errors and run again.

**Comment by edandersen** [comment]
Just added a home.cshtml.


edandersen/core-admin wrote:

What did you do to fix this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
