### ISSUE TITLE
Foreign key relationship in .Net 5.0

### ISSUE THREAD

**Issue by murilomendes** [edandersen/core-admin#73]
Hey guys.

I'm trying to add the DataNotation of Relationship in the Models and "[Display(AutoGenerateField = false)]" and "[ForeignKey("ChildId")]". But it doesn't appears in the dropdown list style. 

It works in .net 5.0 or just in .net 6?

Thanks!

**Comment by edandersen** [comment]
Hiya - this will just be in the .NET 6.0 version.

**Comment by murilomendes** [comment]
Awesome!
