### ISSUE TITLE
Show page for the Records

### ISSUE THREAD

**Issue by murilomendes** [edandersen/core-admin#75]
Hey ho! 
It's me again. 

Edandersen, do you have any plan to add a show view for the records? If you allow me, let me suggest something: 
In Ruby on Rails we have a lib called "Administrate" it's a robust admin panel. There we can navigate in the records through the foreign keys. You can check how it works in this demo:

https://administrate-demo.herokuapp.com/admin
[Administrate in Github](https://github.com/thoughtbot/administrate)

The lib is powered by Thoughtbot, a very nice company.

It would be amazing in .Net.

Thank you so much!!

**Comment by edandersen** [comment]
I see - view pages for each entity and a list of entities that have it as a foreign key? Doable...
________________________________
From: M.M. ***@***.***>
Sent: Tuesday, July 26, 2022 8:33:46 PM
To: edandersen/core-admin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [edandersen/core-admin] Show page for the Records (Issue #75)


Hey ho!
It's me again.

Edandersen, do you have any plan to add a show view for the records? If you allow me, let me suggest something:
In Ruby on Rails we have a lib called "Administrate" it's a robust admin panel. There we can navigate in the records through the foreign keys. You can check how it works in this demo:

https://administrate-demo.herokuapp.com/admin
Administrate in Github<https://github.com/thoughtbot/administrate>

The lib is powered by Thoughtbot, a very nice company.

It would be amazing in .Net.

Thank you so much!!

**Comment by murilomendes** [comment]
Exactly!!

The master details in the page what have the relationship one-to-many would be awesome. :)

**Comment by edandersen** [comment]
I'll add it to the list :-)
________________________________

**Comment by murilomendes** [comment]
Thank you so much :)
