### ISSUE TITLE
How to Edit templates 

### ISSUE THREAD

**Issue by FrancXPT** [edandersen/core-admin#98]
I want to add a button to a view to import a csv and or to add an action.
is there a way to achieve this or it needs to be added to the repo.

**Comment by edandersen** [comment]
You can override templates by copying one of the cshtml files from the class library in this project into the same path on your host project. Cshtml files in your host project will override the ones in the package.

________________________________
From: Achraf BenBamoula ***@***.***>
Sent: Saturday, January 6, 2024 5:11:14 PM
To: edandersen/core-admin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [edandersen/core-admin] How to Edit templates (Issue #98)


I want to add a button to a view to import a csv and or to add an action.
is there a way to achieve this or it needs to be added to the repo.

**Comment by FrancXPT** [comment]
Thank you, It would be Better to have it mentioned on the Docs for new Devs.
